const latestData = [
    {
        "category" : "New Arrival",
        "url" : "/latest/latest-1.png",
        "info" : "Comfort Handy Craft",
        "info2" : "$42.00",
        "info3" : "$65.00",
        "w" : 223,
        "h" : 229,
    },
    {
        "category" : "New Arrival",
        "url" : "/latest/latest-2.png",
        "info" : "Comfort Handy Craft",
        "info2" : "$42.00",
        "info3" : "$65.00",
        "w" : 245,
        "h" : 245,
    },
    {
        "category" : "New Arrival",
        "url" : "/latest/latest-3.png",
        "info" : "Comfort Handy Craft",
        "info2" : "$42.00",
        "info3" : "$65.00",
        "w" : 222,
        "h" : 222,
    },
    {
        "category" : "New Arrival",
        "url" : "/latest/latest-4.png",
        "info" : "Comfort Handy Craft",
        "info2" : "$42.00",
        "info3" : "$65.00",
        "w" : 267,
        "h" : 277,
    },
    {
        "category" : "New Arrival",
        "url" : "/latest/latest-5.png",
        "info" : "Comfort Handy Craft",
        "info2" : "$42.00",
        "info3" : "$65.00",
        "w" : 303,
        "h" : 264,
    },
    {
        "category" : "New Arrival",
        "url" : "/latest/latest-6.png",
        "info" : "Comfort Handy Craft",
        "info2" : "$42.00",
        "info3" : "$65.00",
        "w" : 360,
        "h" : 261,
    },
    {
        "category" : "New Arrival",
        "url" : "/assets/images/latest5.png",
        "info" : "Comfort Handy Craft",
        "info2" : "$42.00",
        "info3" : "$65.00"
    },
    {
        "category" : "New Arrival",
        "url" : "/assets/images/latest6.png",
        "info" : "Comfort Handy Craft",
        "info2" : "$42.00",
        "info3" : "$65.00"
    },
    {
        "category" : "Best Seller",
        "url" : "https://res.cloudinary.com/softenin/image/upload/v1662972642/sample.jpg",
        "info" : "Comfort Handy Craft",
        "info2" : "$42.00",
        "info3" : "$65.00",
        "w" : 267,
        "h" : 267,
    },
    {
        "category" : "Best Seller",
        "url" : "https://res.cloudinary.com/softenin/image/upload/v1662972642/sample.jpg",
        "info" : "Comfort Handy Craft",
        "info2" : "$42.00",
        "info3" : "$65.00",
        "w" : 267,
        "h" : 267,
    },
    {
        "category" : "Best Seller",
        "url" : "https://res.cloudinary.com/softenin/image/upload/v1662972642/sample.jpg",
        "info" : "Comfort Handy Craft",
        "info2" : "$42.00",
        "info3" : "$65.00",
        "w" : 267,
        "h" : 267,
    },
    {
        "category" : "Best Seller",
        "url" : "https://res.cloudinary.com/softenin/image/upload/v1662972642/sample.jpg",
        "info" : "Comfort Handy Craft",
        "info2" : "$42.00",
        "info3" : "$65.00",
        "w" : 267,
        "h" : 267,
    },
    {
        "category" : "Best Seller",
        "url" : "https://res.cloudinary.com/softenin/image/upload/v1662972642/sample.jpg",
        "info" : "Comfort Handy Craft",
        "info2" : "$42.00",
        "info3" : "$65.00",
        "w" : 267,
        "h" : 267,
    },
    {
        "category" : "Best Seller",
        "url" : "https://res.cloudinary.com/softenin/image/upload/v1662972642/sample.jpg",
        "info" : "Comfort Handy Craft",
        "info2" : "$42.00",
        "info3" : "$65.00",
        "w" : 267,
        "h" : 267,
    },
    {
        "category" : "Featured",
        "url" : "https://res.cloudinary.com/softenin/image/upload/v1662972671/cld-sample-4.jpg",
        "info" : "Comfort Handy Craft",
        "info2" : "$42.00",
        "info3" : "$65.00",
        "w" : 267,
        "h" : 267,
    },
    {
        "category" : "Featured",
        "url" : "https://res.cloudinary.com/softenin/image/upload/v1662972671/cld-sample-4.jpg",
        "info" : "Comfort Handy Craft",
        "info2" : "$42.00",
        "info3" : "$65.00",
        "w" : 267,
        "h" : 267,
    },
    {
        "category" : "Featured",
        "url" : "https://res.cloudinary.com/softenin/image/upload/v1662972671/cld-sample-4.jpg",
        "info" : "Comfort Handy Craft",
        "info2" : "$42.00",
        "info3" : "$65.00",
        "w" : 267,
        "h" : 267,
    },
    {
        "category" : "Featured",
        "url" : "https://res.cloudinary.com/softenin/image/upload/v1662972671/cld-sample-4.jpg",
        "info" : "Comfort Handy Craft",
        "info2" : "$42.00",
        "info3" : "$65.00",
        "w" : 267,
        "h" : 267,
    },
    {
        "category" : "Featured",
        "url" : "https://res.cloudinary.com/softenin/image/upload/v1662972671/cld-sample-4.jpg",
        "info" : "Comfort Handy Craft",
        "info2" : "$42.00",
        "info3" : "$65.00",
        "w" : 267,
        "h" : 267,
    },
    {
        "category" : "Featured",
        "url" : "https://res.cloudinary.com/softenin/image/upload/v1662972671/cld-sample-4.jpg",
        "info" : "Comfort Handy Craft",
        "info2" : "$42.00",
        "info3" : "$65.00",
        "w" : 267,
        "h" : 267,
    },
    {
        "category" : "Special Offer",
        "url" : "https://res.cloudinary.com/softenin/image/upload/v1662972670/cld-sample.jpg",
        "info" : "Comfort Handy Craft",
        "info2" : "$42.00",
        "info3" : "$65.00",
        "w" : 267,
        "h" : 267,
    },
    {
        "category" : "Special Offer",
        "url" : "https://res.cloudinary.com/softenin/image/upload/v1662972670/cld-sample.jpg",
        "info" : "Comfort Handy Craft",
        "info2" : "$42.00",
        "info3" : "$65.00",
        "w" : 267,
        "h" : 267,
    },
    {
        "category" : "Special Offer",
        "url" : "https://res.cloudinary.com/softenin/image/upload/v1662972670/cld-sample.jpg",
        "info" : "Comfort Handy Craft",
        "info2" : "$42.00",
        "info3" : "$65.00",
        "w" : 267,
        "h" : 267,
    },
    {
        "category" : "Special Offer",
        "url" : "https://res.cloudinary.com/softenin/image/upload/v1662972670/cld-sample.jpg",
        "info" : "Comfort Handy Craft",
        "info2" : "$42.00",
        "info3" : "$65.00",
        "w" : 267,
        "h" : 267,
    },
    {
        "category" : "Special Offer",
        "url" : "https://res.cloudinary.com/softenin/image/upload/v1662972670/cld-sample.jpg",
        "info" : "Comfort Handy Craft",
        "info2" : "$42.00",
        "info3" : "$65.00",
        "w" : 267,
        "h" : 267,
    },
    {
        "category" : "Special Offer",
        "url" : "https://res.cloudinary.com/softenin/image/upload/v1662972670/cld-sample.jpg",
        "info" : "Comfort Handy Craft",
        "info2" : "$42.00",
        "info3" : "$65.00",
        "w" : 267,
        "h" : 267,
    },
]

export default latestData;